spring.application.name=Demostracion

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=test
spring.data.mongodb.username=MiConexion
#spring.data.mongodb.password=
#mongodb://localhost:27017/
